### PR TITLE
Update libMesh license and features 

### LINKED ISSUE #12: libMesh license is LGPL not GPL

### PR DESCRIPTION
**Pull request by dschwen**
Closes #12

### CODE REVIEW

**Comment by dschwen** [comment]
Ping @jwpeterson

**Comment by roystgnr** [comment]
This is all correct (if still incomplete, but no need to go on forever with a long tail of successively less commonly-used element and I/O types)

**Comment by dschwen** [comment]
@kostyfisik, I did not run `generate-comparison.py` in this PR. If this gets merged first I can rebase and rerun it in #15 (saw the script too late and if I add it onto this PR my other PR will get conflicts).

**Comment by kostyfisik** [comment]
@dschwen @roystgnr Thank you for your contribution!

**Comment by kostyfisik** [comment]
@dschwen Note, I have regenerated tables at GitHub, HTML, and also updated it on wikipedia.

**Pull request merged**
