### PR TITLE
Update comsol.profile

### PR DESCRIPTION
**Pull request by magnusringh**
This update is now complete but the template above does not include some of the "Other" features that I can see on the Wikipedia page. Some of them apply to COMSOL. How can I add those ("Multiphysics" and "Optimization Solvers", for example.

### CODE REVIEW

**Comment by kostyfisik** [comment]
You can add them as new keys with ":" in the end, e.g.

multiphysics:

Note that Comsol has matrix-free option, it is available since 5.1 https://www.comsol.com/release/5.1/studies-and-solvers

**Comment by kostyfisik** [comment]
There are two types of mesh adaptivity, when you fully rebuild mesh or when you just refine (few) needed mesh elements. When you write "full adaptive" does it mean that they have implemented the second option too?

**Comment by magnusringh** [comment]
Hi,

Thanks! How can I edit the version I submitted earlier today so that I
don't have to reenter everything.

Best regards,
Magnus Ringh

**Comment by kostyfisik** [comment]
You can just continue with edits in your copy of this project at https://github.com/magnusringh/FEA-compare/tree/patch-3 I will see the changes here automaticaly.

**Comment by magnusringh** [comment]
Hi,

Yes, the mesh adaptivity is COMSOL is fully flexible, available for
stationary, eigenvalue, and time-dependent simulations, for the entire
geometry or parts, by recreating the full mesh or by refining chosen mesh
elements.

Best regards,
Magnus Ringh

**Comment by magnusringh** [comment]
Hi,

Should be complete now.

Best regards,
Magnus Ringh

**Comment by kostyfisik** [comment]
Great! Thank you a lot!

**Pull request merged**
