### PR TITLE
Profile for MFEM

### LINKED ISSUE #6: Compare with MFEM
Some discussion is here https://github.com/mfem/mfem/issues/90

### PR DESCRIPTION
**Pull request by pazner**
This adds a profile for the [MFEM](https://mfem.org) finite element library.

Resolves #6.

### CODE REVIEW

**Comment by kostyfisik** [comment]
@pazner @tzanio Thank you for your contribution! MFEM looks to have a lot of progress since I looked to it previous time!

**Comment by kostyfisik** [comment]
@tzanio  Note, there is broken link http://mfem.github.io/doxygen/html/ex25_8cpp_source.html at https://mfem.org/features/  
Screenshot from 2020-07-03 13-05-51

**Comment by tzanio** [comment]
>  there is broken link http://mfem.github.io/doxygen/html/ex25_8cpp_source.html at https://mfem.org/features/

This is because we are updating the Doxygen documentation on releases, while the website is updated after new features are merged in master. Maybe we should change this policy...

**Comment by tzanio** [comment]
A comment and a question:

- The HIP row probably belongs right after the CUDA one
- How will the update of https://en.wikipedia.org/wiki/List_of_finite_element_software_packages be triggered?

**Comment by kostyfisik** [comment]
HIP seems to be not a mainstream feature yet. This will add a sparse row for any other package in comparison (which equals to no, but that is not very informative). Actually, without your note about CUDA I would fail to recognize what it stands for.
Feel free to start an issue about a better list of sorted keys used for comparison, and as soon as there are other developers (not from MFEM) to support you I will be happy to change this. At the moment it looks like GPU computing equals CUDA, most researchers do not care about other options.

I've updated wiki page and added a note to README on this.

**Comment by tzanio** [comment]
Do you know why the Wikipedia change was reverted: https://en.wikipedia.org/w/index.php?title=List_of_finite_element_software_packages&action=history ?

**Comment by kostyfisik** [comment]
No idea. I have created a wiki account and updated the table once again.

**Comment by tzanio** [comment]
Did you see this: https://en.wikipedia.org/w/index.php?title=List_of_finite_element_software_packages&action=history?

**Comment by kostyfisik** [comment]
I really hope this guy has good intentions. Feel free to add your 2 cents to help to advance FEM topic https://en.wikipedia.org/wiki/Talk:List_of_finite_element_software_packages#Feature_comparison_table

**Comment by kostyfisik** [comment]
It turned out that this feature table is not Wiki policy compliant, I will try to resolve this issue and post it again.

**Comment by tzanio** [comment]
@kostyfisik I am very sorry about the trouble and I appreciate that you are working with the editors to fit the table in the Wikipedia standards. We have some work to do ourselves with the MFEM page there.

**Comment by kostyfisik** [comment]
@tzanio Let me know if I can help you with this. I have added my comment at https://en.wikipedia.org/wiki/Talk:MFEM, however, I am not capable to track it (for some reasons wikipedia notifications to not work for me).

**Pull request merged**
