### PR TITLE
Update table.html

### PR DESCRIPTION
**Pull request by magnusringh**
Added missing information for COMSOL and fixed a typo in the Feature column.

### CODE REVIEW

**Comment by kostyfisik** [comment]
@magnusringh Thank you a lot for your contribution! Could you please fill this information into https://github.com/kostyfisik/FEA-compare/blob/master/profiles/comsol.profile ? Note, that HTML table and table in Wikipedia format are both generated from these *.profile files. BTW, COMSOL has some matrix free implementation (and you put "No"), however, I am not aware of any benchmarks for this.

**Comment by magnusringh** [comment]
Hi, I did not know that. I'll update the profile file instead.

**Comment by kostyfisik** [comment]
See the related information about tables generated and the descripion of *.profile format on the main page of this project https://github.com/kostyfisik/FEA-compare#overview

**Comment by magnusringh** [comment]
Hi,

From where did you get the information that COMSOL has some matrix-free
implementation? It doesn't use a mesh for 0D ODEs and DAEs, but I don't
think that that counts. For simulations with a geometry, a mesh is always
needed.

Magnus

**Comment by magnusringh** [comment]
Hello,

I'm not sure if you can do anything about it, but the information on the
linked Wikipedia page is still not updated.

Best regards,
Magnus

**Comment by kostyfisik** [comment]
@magnusringh Sorry, I missed your first message. Note, that mesh-free is not the same as matrix free. Matrix-free setup done well can lead to a total speedup of computations by a factor of ten, see the comparison versus traditional sparse matrix approach. https://www.dealii.org/developer/doxygen/deal.II/step_37.html#Comparisonwithasparsematrix 

For Comsol they just claim that it saves memory "Matrix-Free Domain-Decomposition Solver

A new solver option allows computing without explicitly forming the global system matrix. This can dramatically reduce memory requirements for large simulations. "  from https://www.comsol.com/release/5.1/studies-and-solvers 

Note, I`ve just updtated the Wikipedia entry https://en.wikipedia.org/wiki/List_of_finite_element_software_packages#Feature_comparison

**Comment by magnusringh** [comment]
Thanks!

**Pull request closed without merging**
